---
version: '3'

tasks:
  install-cross-tools:
    desc: Install cross-compilation tools for aarch64 Linux
    cmds:
      - |
        if [ "$TARGET" != "aarch64-unknown-linux-gnu" ]; then
          echo "Skipping cross-tools: TARGET=${TARGET}"
          exit 0
        fi
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> "$GITHUB_ENV"
    requires:
      vars:
        - TARGET

  compile:
    desc: Compile tool from crates.io or git
    cmds:
      - |
        SOURCE=$(jq -r '.source // "crate"' tool.json)
        if [ "$SOURCE" = "git" ]; then
          UPSTREAM_URL=$(jq -r .upstream tool.json)
          cargo install \
            --git "${UPSTREAM_URL}" \
            --tag "v${VERSION}" \
            --target "${TARGET}" \
            --root ./dist \
            --locked || \
          cargo install \
            --git "${UPSTREAM_URL}" \
            --tag "v${VERSION}" \
            --target "${TARGET}" \
            --root ./dist
        else
          CRATE=$(jq -r .crate tool.json)
          cargo install "${CRATE}" \
            --version "${VERSION}" \
            --target "${TARGET}" \
            --root ./dist \
            --locked || \
          cargo install "${CRATE}" \
            --version "${VERSION}" \
            --target "${TARGET}" \
            --root ./dist
        fi
    requires:
      vars:
        - VERSION
        - TARGET

  package:
    desc: Package binary as tarball with sha256 checksum
    cmds:
      - |
        ARCHIVE="${TOOL_NAME}-${TARGET}.tar.gz"
        cd dist/bin
        tar czf "../../${ARCHIVE}" "${TOOL_NAME}"
        cd ../..
        shasum -a 256 "${ARCHIVE}" > "${ARCHIVE}.sha256"
    requires:
      vars:
        - TOOL_NAME
        - TARGET

  release:
    desc: Create GitHub Release with artifacts
    cmds:
      - |
        gh release create "v${VERSION}" \
          --title "${TOOL_NAME} v${VERSION}" \
          --notes "Prebuilt binaries for ${TOOL_NAME} v${VERSION} from upstream." \
          artifacts/*
    requires:
      vars:
        - TOOL_NAME
        - VERSION
        - GH_TOKEN
